# yaml-language-server: $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/packages/cspell-tools/cspell-tools.config.schema.json

targets:
  - name: nolebase
    targetDirectory: .
    compress: false
    format: trie3
    sources:
      - src/nolebase.dic.txt
    generateNonStrict: true

checksumFile: true
