version: "0.2"
ignorePaths:
  - "**/*.tire"
dictionaryDefinitions:
  - name: nolebase
    path: ./src/nolebase.dic.txt
    addWords: true
dictionaries:
  - nolebase
words:
  - antfu
  - bumpp
  - mdash
  - nolebase
  - unocss
ignoreWords: []
import: []
